### PR TITLE
A programmatic scene setup example and some minor improvements.

### PR DESCRIPTION
**Pull request by skesgin**
The improvements are mainly around reducing the amount of boilerplate code which makes reading, understanding and using the code of the framework easier.

### CODE REVIEW

**Comment by McNopper** [comment]
Wow, you did a lot of work. Give me some time, I will look at it.

**Comment by skesgin** [comment]
No rush. The CI build failed anyway. GCC and Clang does not seem to like my macros. I will look at it tomorrow and see what's wrong.


I got some ideas that I believe would make the use and the maintenance of the framework code a bit easier. I can take those on if you are interested. I left some comments in the code marked with "TODO:", they explain some of the ideas I have.


Let me know if you want to discuss.


Serkan


________________________________

**Comment by McNopper** [comment]
Mabye we do things step by step:
Please make smaller, atomic integration packages.
It is also for me easier to review.

**Comment by skesgin** [comment]
As requested, will split the PR into smaller pieces.

**Pull request closed without merging**
