### PR TITLE
Validation helpers

### PR DESCRIPTION
**Pull request by skesgin**
Introduced helper macros for validating object instances, operation results and conditions to reduce the amount of boilerplate code. Updated the Example04 project to use the helper macros which reduced the number of lines of code from 1413 to 1191. Less code is easier to read and follow, and this reduces the barrier for entry for developers to adopt the framework.

### CODE REVIEW

**Comment by skesgin** [comment]
If you accept this one, I can place a PR for the rest of the improvements I made. Unfortunately, they mostly rely on the macros included in this PR.

**Comment by McNopper** [comment]
First at all, thank you for providing the improvements.
I will check them the next days but on a first view they seem fine.
For the macros, I will probably add the VKTS_ before. Also, all feature TODOs will become issues - these are some of yours and mine.
Regarding the input configuration, I have planned to encode this in a JSON file. The core module can load it and then this information can be passed to modules, which do need them.
Finally, I still need the option that only e.g. a specific gamepad is enabled. Or did you solve, having two gamepads and e.g. two players.
Again, thank you very much for your contribution. I will have a closer look indeed.

**Comment by McNopper** [comment]
I like the the VALIDATION macros. Can you please add VKTS_ before?
I close this pull request, as some changes have been done.

**Comment by McNopper** [comment]
Also, lets chat on gitter, before you make any further chnages:
https://gitter.im/McNopper/Lobby

**Comment by McNopper** [comment]
It is great, that you want to contribute. But I do not want to demotivate you, as I have no accepted everything so far.
So lets chat, and we can clarify things in advance.
Okay for you?

**Comment by McNopper** [comment]
Just tell me, when you are online.

**Comment by skesgin** [comment]
I'm online.

**Pull request closed without merging**
